# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Validate

on:
  push:
    branches: [ "test" ]
  
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    env:
      IMAGE_NAME: gophers-api
      REGISTRY: quay.io/skhoury
    steps:
      - uses: actions/checkout@v4

      - name: Prepare auth
        run: |
          auth_file=$(cat << 'EOF1'
          {
            "auths": {
              "registry.redhat.io": {
                "auth": "${{ secrets.REGISTRY_TOKEN }}",
                "email": "skhoury@redhat.com"
              }
            }
          }
          EOF1
          )
          echo "$auth_file" > /tmp/auth.json

      - name: Podman login
        uses: redhat-actions/podman-login@main
        with:
          registry: quay.io
          username: skhoury
          password: ${{ secrets.QUAY_TOKEN }}
          auth_file_path: /tmp/auth.json
      
      - name: Buildah build
        id: build-image
        uses: redhat-actions/buildah-build@main
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          containerfiles: ./Dockerfile
          extra_args: "--authfile /tmp/auth.json"
          tags: latest
      - name: Buildah push
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: skhoury
          password: ${{ secrets.QUAY_TOKEN }}

     
      - name: Attest
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push-to-quay.outputs.digest }}
          push-to-registry: true